[package]
name = "qmpo-core"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Core library for qmpo directory URI handler"

[dependencies]
url = { version = "2.5.8", default-features = false }
percent-encoding = "2.3.2"
thiserror = "2.0.18"
